#include <pebble.h>



#define SCREEN_WIDTH 144
#define SCREEN_HEIGHT 168

#define CITY_SPLIT 29
#define COUNTRY_SPLIT 45
#define STEP_SPLIT 45

#define DEFAULT_WALK_ID "kpouer~7362688"

#define QUERY_TYPE_BEAUTIFULWALK 1
//#define foo(x) ((x) > 32 ? (x) : (2 * (x)))

#define KEY_QUERY 1

#define KEY_NEXTCITY 20
#define KEY_NEXTCITYDONE 21
#define KEY_NEXTCITYTOTAL 22
#define KEY_NEXTCOUNTRY 23
#define KEY_NEXTCOUNTRYDONE 24
#define KEY_NEXTCOUNTRYTOTAL 25
#define KEY_NEXTSTEP 26
#define KEY_NEXTSTEPDONE 27
#define KEY_NEXTSTEPTOTAL 28
#define KEY_TOTALDONE 29
#define KEY_WALKID 30
#define KEY_RACEID 31

#define BAR_HEIGHT 10
#define BAR_SHIFT 2
#define BAR_MAX_LENGTH (SCREEN_WIDTH - 2 * BAR_SHIFT)

#define FONT_TITLE   FONT_KEY_GOTHIC_24_BOLD
#define FONT_DEFAULT FONT_KEY_GOTHIC_14_BOLD
#define FONT_TITLE_HEIGHT   24
#define FONT_DEFAULT_HEIGHT 14 + 2

#define TITLE_2_Y       FONT_TITLE_HEIGHT
#define TITLE_3_Y       TITLE_2_Y + FONT_TITLE_HEIGHT
#define CITY_Y          TITLE_3_Y + FONT_TITLE_HEIGHT + 1
#define CITY_BAR_Y      CITY_Y + FONT_DEFAULT_HEIGHT + 2
#define COUNTRY_Y       CITY_BAR_Y + BAR_HEIGHT
#define COUNTRY_BAR_Y   COUNTRY_Y + FONT_DEFAULT_HEIGHT + 2
#define NEXT_STEP_Y     COUNTRY_BAR_Y + BAR_HEIGHT
#define NEXT_STEP_BAR_Y NEXT_STEP_Y + FONT_DEFAULT_HEIGHT + 2


#define STRUCT_VERSION 1

#define KEY_PERSISTDATA_VERSION 1
#define KEY_PERSISTDATA_WALKID 2
#define KEY_PERSISTDATA 30